package com.example.analytics.analytics

object Events {
    const val SPLASH_CREATION_EVENT = "SPLASH_CREATION_EVENT"
    const val FEATURE_HOME_ENTRY_POINT_CREATION_EVENT = "FEATURE_HOME_ENTRY_POINT_CREATION_EVENT"
    const val FEATURE_ONE_ENTRY_POINT_CREATION_EVENT = "FEATURE_ONE_ENTRY_POINT_CREATION_EVENT"
}